input_dir: "./posts"
templates_dir: "./templates"
output_dir: "/var/www/html"
badges_dir: "./badges"
index_template_path: "./templates/index.html"
tags_index_template_path: "./templates/tags.html"
tag_page_template_path: "./templates/tag.html"
author: "Your Name Here"
blog_name: "Generic Blog Name"
description: "This is my blog. There are many like it, but this one is mine"
email: harrison.page@harrison.page
fediverse_creator: @harrisonpage@defcon.social
copyright: "2024"
lang: "en"
language: "en-us"
locale: "en_US"
badges:
  - title: "Home Page"
    url: "https://harrison.page"
    icon: "home.svg"
  - title: "Photography"
    url: "https://harrison.photography"
    icon: "camera.svg"
  - title: "Instagram"
    url: "https://instagram.com/harrisonpage"
    icon: "instagram.svg"
  - title: "Github: harrisonpage/draft"
    url: "https://github.com/harrisonpage/draft"
    icon: "github.svg"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/harrisonpage/"
    icon: "linkedin.svg"
  - title: "Share"
    icon: "share.svg"
    id: "share"
css_files:
  - "https://example.com/stylesheet.css"
js_files:
  - "https://example.com/script.js"
pages:
  - template: about.html
    title: About
    link: about
  - template: colophon.html
    title: Colophon
    link: colophon
url: "https://example.com"
base_path: "draft"
back_label: "Back"
search:
    enabled: false

