input_dir: "./posts"
templates_dir: "./templates"
output_dir: "/var/www/html"
index_template_path: "./templates/index.html"
tags_index_template_path: "./templates/tags.html"
tag_page_template_path: "./templates/tag.html"
author: "Your Name Here"
blog_name: "Generic Blog Name"
description: "This is my blog. There are many like it, but this one is mine"
copyright: "2024"
language: "en-us"
css_files:
  - "https://example.com/stylesheet.css"
js_files:
  - "https://example.com/script.js"
url: "https://example.com"
base_path: "draft"
back_label: "Back"